# Generated by Django 3.2.18 on 2023-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_investments', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='identifier',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
