# Generated by Django 3.2.18 on 2023-03-26 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_investments', '0007_alter_loan_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='type',
            field=models.CharField(choices=[('FUNDING', 'Funding'), ('PRINCIPAL_REPAYMENT', 'Principal Repayment'), ('INTEREST_REPAYMENT', 'Interest Repayment')], max_length=20),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='ta_investments.portfolio'),
        ),
    ]
